server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost/db_academia
    username: postgres
    password: root

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update


